blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$',
            views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/',
         views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/',
         views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
]

bookmark/urls.py
from django.urls import path
from bookmark.views import BookmarkLV, BookmarkDV

app_name = 'bookmark'
urlpatterns = [
    path('',BookmarkLV.as_view(), name='index'),
    path('<int:pk>/',BookmarkDV.as_view(), name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView

# from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", HomeView.as_view(), name='home'),

    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),

    # path('bookmark/', BookmarkLV.as_view(), name='index'),
    # path('bookmark/<int:pk>/', BookmarkDV.as_view(), name='detail'),
]

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name="TITLE", max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

bookmark/models.py
from django.db import models

# Create your models here.
class Bookmark(models.Model):
    title = models.CharField("Title", max_length=100, blank=True)
    url = models.URLField("URL", unique=True)

    def __str__(self):
        return self.title

blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from blog.models import Post

# Create your views here.

#--- ListView


class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

#--- DetailView


class PostDV(DetailView):
    model = Post

#--- ArchiveView


class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True
    #month_format = '%b'


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'

bookmark/views.py
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

mysite/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

blog/templates/blog/post_all.html
{% extends 'base.html' %}

{% block title %}post_all.html{% endblock %}

{% block content%}
    <h1>Blog List</h1>
    <br />

    {% for post in posts %}
    <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
    {{ post.modify_dt|date:"N D, Y" }}
    <p>{{ post.description }}</p>
    {% endfor %}

    <br />

    <div>
        <span>
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
            {% endif %} Page {{ page_obj.number }} of
            {{page_obj.paginator.num_pages}} {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

blog/templates/blog/post_archive.html
{% extends 'base.html' %}

{% block title %}post_archive.html{% endblock %}

{% block content %}

    <h1>Post Archives until {%now "N d, Y" %}</h1>

    {% for date in date_list %}
    <a href="{% url 'blog:post_year_archive' date|date:'Y' %}" class="btn btn-outline-primary btn-sm mx-1">
        Year-{{ date|date:"Y" }}
    </a>
    {% endfor %}

    <br /><br />

    <div>
        <ul>
            {% for post in object_list %}
            <li class="h5">
                {{ post.mdify_dt|date:"Y-m-d"}}&emsp;
                <a href="{{post.get_absolute_url}}">
                    <strong>{{post.title}}</strong>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends 'base.html' %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}
    <h1>Post Archives for {{ day|date:"N d, Y"}}</h1>
    <br><br>
    <div>
        <ul>
            {% for post in object_list %}
            <li class="h5">
                {{ post.modify_dt|date:"Y-m-d"}}&emsp;<a
                    href="{{post.get_absolute_url}}"
                    ><strong>{{post.title}}</strong></a
                >
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends 'base.html' %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}
    <h1>Post Archives for {{ month|date:"N, Y"}}</h1>

    <div>
        <ul>
            {%for post in object_list %}
            <li class="h5">
                {{ post.mdify_dt|date:"Y-m-d"}}&emsp;<a
                    href="{{post.get_absolute_url}}"
                    ><strong>{{post.title}}</strong></a
                >
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends 'base.html' %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}
    <h1>Post Archives for {{ year|date:"Y"}}</h1>
    {% for date in date_list %}
        <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}" class="btn btn-outline-primary btn-sm mx-1">
            {{date|date:"F"}}
        </a>
    {% endfor %}
    <br /><br />
    <div>
        <ul>
            {%for post in object_list %}
            <li class="h5">
                {{ post.mdify_dt|date:"Y-m-d"}}&emsp;<a
                    href="{{post.get_absolute_url}}"
                    ><strong>{{post.title}}</strong></a
                >
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %}post_detail.html{% endblock %}

{% block content %}
    <h2>{{ object.title }}</h2>

    <p>
        {%if object.get_next%}
        <a
            href="{{object.get_next.get_absolute_url}}"
            title="View previous post"
            ><i class="fas fa-arrow-circle-left"></i> {{object.get_next}}
        </a>
        {%endif%}
        {%if object.get_previous%}
        <a
            href="{{object.get_previous.get_absolute_url}}"
            title="View next post"
            >{{object.get_previous}}<i class="fas fa-arrow-circle-right"></i> 
        </a>
        {%endif%}
    </p>

    <p>{{object.mdify_dt|date:"j F Y"}}</p>
    <br />
    <div>{{object.content|linebreaks}}</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}bookmark_detail.html{% endblock %}

{% block content %}
    <h1>{{ object.title }}</h1>
    <ul>
        <li>URL : <a href="{{ object.url }}" target="_blank">{{ object.url }}</a></li>
    </ul>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}bookmark_list.html{% endblock %}

{% block content %}
    <h1>Bookmark List</h1>
    <br>
    <ul>
        {% for bookmark in object_list %}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{bookmark}}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %}Django Web Programming{% endblock %}</title>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
        />
        {% block extra-style %}{% endblock %}
    </head>
    <body style="padding-top: 90px">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
            <div class="container-fluid">
                <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Django - Python Web Programming</span>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div
                    class="collapse navbar-collapse"
                    id="navbarSupportedContent"
                >
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item mx-1 btn btn-primary">
                            <a
                                class="nav-link active"
                                aria-current="page"
                                href="{% url 'home' %}"
                                >Home</a
                            >
                        </li>
                        <li class="nav-item mx-1 btn btn-primary">
                            <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a>
                        </li>
                        <li class="nav-item mx-1 btn btn-primary">
                            <a class="nav-link text-white" href="{% url 'blog:index' %}">Blog</a>
                        </li>
                        <li class="nav-item mx-1 btn btn-primary">
                            <a class="nav-link text-white" href="">Photo</a>
                        </li>
                        <li class="nav-item dropdown mx-1 btn btn-primary">
                            <a
                                class="nav-link dropdown-toggle text-white"
                                href="#"
                                id="navbarDropdown"
                                role="button"
                                data-bs-toggle="dropdown"
                                aria-expanded="false"
                            >
                                Util
                            </a>
                            <ul
                                class="dropdown-menu"
                                aria-labelledby="navbarDropdown"
                            >
                                <li>
                                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                                </li>
                                <div class="dropdown-divider"></div>
                                <li>
                                    <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="">Search</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
                        <input
                            class="form-control mr-sm-2"
                            type="search"
                            placeholder="global search"
                            aria-label="Search"
                            name="search_word"
                        />
                    </form>
                </div>
            </div>
        </nav>

        <div class="container">{% block content %}{% endblock %}</div>

        {% block footer %}{% endblock %}
    </body>
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"
    ></script>
    <script src="https://kit.fontawesome.com/c22609eba1.js" crossorigin="anonymous"></script>
</html>

templates/home.html
{% extends 'base.html' %} 

{% load static %}

{% block title %}home.html{% endblock %} 

{% block extra-style %}
<style type="text/css">
    .home-image {
        background-image: url("{% static 'img/lion.jpeg' %}");
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100%;
        height: 500px;
        border-top: 10px solid #ccc;
        border-bottom: 10px solid #ccc;
        padding: 20px 0 0 20px;
    }
    .title {
        color: #c80;
        font-weight: bold;
    }
    .powered {
        position: relative;
        top: 77%;
        color: #cc0;
        font-style: italic;
    }
</style>
{% endblock %}

{%block content%}
    <div class="home-image">
        <h2 class="title">Django - Python Web Programming</h2>
        <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap.</h4>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Bookmark App</h3>
            <p>Bookmark is a Uniform Resource Identifier (URI) taht is stored for later retrieval in any of various storage formats. You can store your own bookmarks by Bookmark application. It's also possible to update or delete your bookmarks.</p>
        </div>
        <div class="col-sm-6">
            <h3>Blog App</h3>
            <p>This application makes it possible to log daily events or write your own interests such as hobbies, techniques, etc. A typical blog combines text, digital images, and links to other blos, web pages, and oter media related to its topics.</p>
        </div>
    </div>

{% endblock %} 

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; 2019 DjangoBook by chae1-1111</div>
</footer>
{% endblock %}